### ISSUE TITLE
java.lang.ClassNotFoundException: org.gradle.api.internal.DynamicObject

### ISSUE THREAD

**Issue by kristofdepypere** [bmuschko/gradle-vagrant-plugin#10]
When applying in gradle 3.1 this plugin throws a ClassNotFoundException. Can this plugin be re-released for gradle 3 ?

**Comment by bmuschko** [comment]
I just released version 2.1 of the plugin that fixes your issue.

**Comment by kristofdepypere** [comment]
Thx, much appreciated
